### ISSUE TITLE
did rx550 lexa works ? 

### ISSUE THREAD

**Issue by Petelin** [George54/EFI-gigabyte-h310m-s2h-2.0-intel-core-I5-9400-uhd-630-rx-550-#1]
same gpu card but not work

**Comment by George54** [comment]
Change the priority of loading the video card in the bios to the rx 550. I
checked my Opencore on catalina. I am writing now using the latest version
of big sur. Everything works. Good luck to you

вт, 16 мар. 2021 г. в 19:46, lin ***@***.***>:
